name: Flake CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  site-build:
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build site
        run: nix --extra-experimental-features "nix-command flakes" build .#site

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/
          commit_message: Deploy website from commit ${{ github.event.head_commit.after }}

